[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", chars = "\u0016" },
  { key = "Return", mods = "Shift", chars = "\u001B\r" },
]

[terminal.shell]
program = "tmux"
args = ["new-session"]
